# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy Events Frontend

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest # add version of this

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: "Checkout"
      - uses: actions/checkout@master # what about staging

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: yarn install
      - run: yarn install # add production flag if production

      - name: rebuild-dependencies
      - run: yarn rebuild node-sass

      - name: yarn build
      - run: yarn build

      - name: linting checks
      - run: yarn lint

      - name: run tests
      - command: yarn test
